version: '3.9'

services:
  postgres:
    image: postgres:17-alpine3.22
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5463:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: bannercounter:latest
    ports:
      - "5454:5454"
    environment:
      - HOST=postgres
      - PORT=5432
      - USER=postgres
      - PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local